### Find All Products
GET http://127.0.0.1:3000/api/products
Accept: application/json

### Find Product Detail
GET http://127.0.0.1:3000/api/products/20
Accept: application/json

### Create Product
POST http://127.0.0.1:3000/api/products
Accept: application/json
Content-Type: application/json

{
  "name": "MS Glow For Man",
  "price": 3500000,
  "sku": "RN-10PRO",
  "stock": 10,
  "category_id": 5
}

### Update Product By Id
PUT http://127.0.0.1:3000/api/products/25
Accept: application/json
Content-Type: application/json

{
  "name": "Smartphone BlackBerry - Black Edition",
  "price": 100,
  "sku": "BB-001",
  "stock": 123,
  "category_id": 4
}

### Delete Product By Id
DELETE http://127.0.0.1:3000/api/products/13
Accept: application/json

### Find All Categories
GET http://127.0.0.1:3000/api/categories
Accept: application/json

### Find Category By Id
GET http://127.0.0.1:3000/api/categories/25
Accept: application/json

### Create Category
POST http://127.0.0.1:3000/api/categories
Accept: application/json
Content-Type: application/json

{
  "name": "Redmi Note 10 Pro"
}

### Update Category By Id
PUT http://127.0.0.1:3000/api/categories/3
Accept: application/json
Content-Type: application/json

{
  "name": "Electronic"
}

### Delete Category By Id
DELETE http://127.0.0.1:3000/api/categories/3
Accept: application/json